# This is a generated file. Not intended for manual editing.
services:
  conversespace.api:
    build:
      context: "F:\\Projects\\ConverseSpace"
      dockerfile: "ConverseSpace.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ConverseSpace.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "conversespace.api:dev"
    ports: []
    volumes:
    - "D:\\Packages\\.nuget\\packages:/home/app/.nuget/packages"
    - "F:\\Projects\\ConverseSpace\\ConverseSpace.API:/app:rw"
    - "F:\\Projects\\ConverseSpace:/src:rw"
    working_dir: "/app"
