# This is a generated file. Not intended for manual editing.
services:
  conversespace.api:
    build:
      context: "F:\\Projects\\ConverseSpace"
      dockerfile: "ConverseSpace.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "conversespace.api:dev"
    ports:
    - "127.0.0.1:57015:57100"
    - "127.0.0.1:57215:57300"
    volumes:
    - "D:\\Packages\\.nuget\\packages:/home/app/.nuget/packages"
    - "F:\\Projects\\ConverseSpace\\ConverseSpace.API:/app:rw"
    - "F:\\Projects\\ConverseSpace:/src:rw"
    - "C:\\Users\\fel4s\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "D:\\Programs\\JetBrains Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\fel4s\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_4_08_22_05_08:/var/opt/rider-debugger:rw"
    working_dir: "/app"
